# Generated by Django 4.2.1 on 2023-05-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombrepaciente', models.CharField(max_length=100)),
                ('fecha_nac', models.DateField()),
                ('Genero', models.CharField(max_length=9)),
                ('numerotelefonico', models.IntegerField()),
                ('historialclinico', models.TextField()),
            ],
        ),
    ]
