# Generated by Django 4.2.1 on 2023-05-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentroClinico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antecedentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='nombrepaciente',
            new_name='nombre_paciente',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='numerotelefonico',
            new_name='numero_telefonico',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='historialclinico',
        ),
        migrations.AddField(
            model_name='paciente',
            name='antecedentes',
            field=models.ManyToManyField(blank=True, to='CentroClinico.antecedentes'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='enfermedades',
            field=models.ManyToManyField(blank=True, to='CentroClinico.enfermedad'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='medicamentos',
            field=models.ManyToManyField(blank=True, to='CentroClinico.medicamento'),
        ),
    ]
