# Generated by Django 4.2.1 on 2023-05-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentroClinico', '0002_antecedentes_enfermedad_medicamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedentes',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
