# Generated by Django 4.2.1 on 2023-05-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentroClinico', '0003_alter_antecedentes_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='antecedentes',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='enfermedades',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='medicamentos',
        ),
        migrations.AddField(
            model_name='paciente',
            name='historial_clinico',
            field=models.TextField(default='Antecedentes_Clinicos'),
        ),
        migrations.DeleteModel(
            name='Antecedentes',
        ),
        migrations.DeleteModel(
            name='Enfermedad',
        ),
        migrations.DeleteModel(
            name='Medicamento',
        ),
    ]
