# Generated by Django 4.2.1 on 2023-05-28 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CentroClinico', '0004_remove_paciente_antecedentes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneroPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_genero', models.CharField(max_length=9)),
            ],
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='Genero',
        ),
        migrations.AddField(
            model_name='paciente',
            name='genero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CentroClinico.generopaciente'),
        ),
    ]
