# Generated by Django 4.2.1 on 2023-05-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentroClinico', '0005_generopaciente_remove_paciente_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='historial_clinico',
            field=models.TextField(default='Antecedentes Clinicos'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numero_telefonico',
            field=models.CharField(max_length=13),
        ),
    ]
