# Generated by Django 4.2.1 on 2023-05-30 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CentroClinico', '0007_citas_medicas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citas_medicas',
            name='nombre_paciente',
        ),
        migrations.DeleteModel(
            name='paciente',
        ),
    ]
