# Generated by Django 4.2.1 on 2023-05-30 15:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CentroClinico', '0008_remove_citas_medicas_nombre_paciente_delete_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas_medicas',
            name='hora_cita',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Pacientecli',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12)),
                ('nombre_paciente', models.CharField(max_length=100)),
                ('fecha_nac', models.DateField()),
                ('numero_telefonico', models.CharField(max_length=13)),
                ('historial_clinico', models.TextField(default='Antecedentes Clinicos')),
                ('genero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CentroClinico.generopaciente')),
            ],
        ),
        migrations.AddField(
            model_name='citas_medicas',
            name='nombre_paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CentroClinico.pacientecli'),
        ),
    ]
